language: c
script:
  - make vars
  - make test/optimized
  - make test/ci
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
